apiVersion: v1
kind: Namespace
metadata:
  name: tsukutter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  namespace: tsukutter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tsukutter
  name: drone
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tsukutter
  name: drone
subjects:
- kind: ServiceAccount
  name: drone
  namespace: tsukutter
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tsukutter
  name: tsukutter
  namespace: tsukutter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tsukutter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: tsukutter
    spec:
      containers:
      - image: kinadu/tsukutter
        imagePullPolicy: Always
        name: tsukutter
        volumeMounts:
        - mountPath: /app/db
          name: data
      - image: kinadu/tsukutter
        imagePullPolicy: Always
        name: tsukutter-bat
        command: ["/app/bat/chk.sh"]
        volumeMounts:
        - mountPath: /app/db
          name: data
        env:
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: tsukutter
              key: twitter_consumer_key
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: tsukutter
              key: twitter_consumer_secret
        - name: TWITTER_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tsukutter
              key: twitter_access_key
        - name: TWITTER_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: tsukutter
              key: twitter_access_secret
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-claim-tsukutter
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: tsukutter
  name: tsukutter
  namespace: tsukutter
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: tsukutter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tsukutter
  namespace: tsukutter
spec:
  rules:
  - host: tsukutter.inajob.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: tsukutter
          servicePort: 80

